Use Bytes directly instead of uint8_t array for pack().
GCC 12.2 on Debian 12 complains that raw might be unused. Replace
with Bytes/std::string and casting data() to uint8_t* instead.

Warning was:

    inlined from 'hilti::rt::Bytes hilti::rt::Address::pack(
      hilti::rt::ByteOrder) const'
      at /src/hilti/runtime/src/types/address.cc:132:54:
      /usr/include/c++/12/bits/char_traits.h:431:56: error:
     'raw' may be used uninitialized [-Werror=maybe-uninitialized]