Disable precompiled headers for gcc CI job.
While mixing GCC and Clang with precompiled headers is an issue for JIT
(JIT always uses Clang to compile modules while precompiled headers are
created with the compiler used to compile Spicy itself), we disable
precompiled headers for the non-JIT, GCC job since GCC emits a
non-suppressible warning, see
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=89808,

    build/hilti/runtime/include/hilti/rt/libhilti.h:3:9: error: #pragma once in main file [-Werror]
        3 | #pragma once
          |         ^~~~
    cc1plus: all warnings being treated as errors

Instead of not treating warnings as errors anymore we disable precompiled
headers in this build since it does not use them anyway.