Don't ignore alloca() return value in test.
Silence warning on Alpine:

    fiber.cc:314:11: error: ignoring return value of 'void*
      __builtin_alloca(long unsigned int)' declared with attribute
      'warn_unused_result' [-Werror=unused-result]